### ISSUE TITLE
Made a non-shouty, RPG focused "character idea generator".

### ISSUE THREAD

**Issue by Matt-Ceb** [soulwire/WTFEngine#15]
Well, for a very weak meaning of "made"...

I started with doing one for Shadowrun:
"Who the Frag is..."
http://enklave-23.de/WTF/

And then I cleaned that one up and put it up on github for others to use for other kinds of systems/worlds/uses.
https://github.com/Matt-Ceb/Random-NPC-Idea-generator

**Comment by soulwire** [comment]
Great stuff! Thanks for sharing and I've added to the project link.
