### ISSUE TITLE
WTF Are My Weekend Plans?

### ISSUE THREAD

**Issue by tjvonp** [soulwire/WTFEngine#22]
I just made one and am setting up the domain as I type this.  Any suggestions on improvements?  Did I change any text you'd rather I didn't?  Any general comments?  Let me know!*

www.wtfplans.com

*Unless you have a better name for the domain.  'Cause, you know, I already bought it, and I'd be bummed if I realized that was something better.

**Comment by tjvonp** [comment]
I've had a problem for a couple of weeks where the site won't move passed the loading animation.  Anyone else had to deal with something like that?

I've been too busy to look into the problem until now.  I thought maybe it had to do with Google updating Google Docs (which I was using to supply the data), but I can't find any evidence that that is right other than that the update happened around the same time my site broke.  

UPDATE:  As I was typing this, I changed it so it is fed by the sample.json.  Now it works!  Therefore, I'm pretty sure it is the fault of Google Docs.  If I find a fix, I'll post it so everyone else will have it on record.  If I haven't posted a fix yet, feel free to toss in your thoughts.

**Comment by soulwire** [comment]
Hey, great site and thanks for the link :) Check out #24 and #25 and sorry for the problem. Google changed the way sheets work but I've added a workaround to fix it. Just replace your `wtf.js` with the latest if you still want to use the live sheet feed. Seems like you got it working anyway though which is great.
