### ISSUE TITLE
We used your WTF engine

### ISSUE THREAD

**Issue by magnarm** [soulwire/WTFEngine#23]
...to create an idea generator for the next big nordic larp. It was super seamless and easy to set up!

http://www.messagefromtheinternet.com/nordiclarp/

**Comment by soulwire** [comment]
Hey - will add to the showcase but also it looks like you're using the live spreadsheet feed to power it. Google broke these so you'll need to update your `wtf.js` script with the latest from this repo. See #24 and #25 for more info.
