### ISSUE TITLE
My version of the WTF Engine is not working

### ISSUE THREAD

**Issue by Nuku** [soulwire/WTFEngine#25]
http://whoismypony.ponyfinder.net/ is failing with a Access-Control-Allow-Origin. My attempts to remedy have failed entirely. Any help at all would be appreciated.

**Comment by Nuku** [comment]
XMLHttpRequest cannot load https://docs.google.com/spreadsheets/d/1URWEIVmdt8owVTJ94d0qUCEvdgFZPlW8Jw1FGq56CYs/pub?output=csv. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://whoismypony.ponyfinder.net' is therefore not allowed access.

**Comment by soulwire** [comment]
Please see #24 

Google unfortunately have changed the way published sheets worked. Is it possible for you to download your spreadsheet and host it yourself, using one of the other `init` methods?

Looking into how to work around this change to docs!

**Comment by Nuku** [comment]
What is the easiest way to get my spreadsheet out into a file that can be reached by wtf?

**Comment by tjvonp** [comment]
I just manually wrote it out into the JSON format.  Might be tedious, but
it got the job done for www.wtfplans.com

**Comment by soulwire** [comment]
@Nuku just about to push an update that should fix this issue so you don't have to change anything!..

**Comment by Nuku** [comment]
@soulwire Alright! Thanks!

**Comment by soulwire** [comment]
Ok, give that a try. All you should have to do is replace your [wtf.js](https://github.com/soulwire/WTFEngine/blob/master/scripts/wtf.js) with the latest and see if that works. It's a quick fix so not thoroughly tested but data is coming through ok for me with the test spreadsheet.

**Comment by Nuku** [comment]
Ok! It didn't get stuck in loading, but it's showing the default data?

**Comment by Nuku** [comment]
Fixed!

**Comment by Nuku** [comment]
Many thanks!

**Comment by soulwire** [comment]
Cool - yeah it looked like what was published at your link was the default data (https://docs.google.com/spreadsheets/d/1URWEIVmdt8owVTJ94d0qUCEvdgFZPlW8Jw1FGq56CYs/pub) what's your spreadsheet key?

**Comment by Nuku** [comment]
Where is this 'key' located?

**Comment by soulwire** [comment]
It'll be the string you pass to the init method: `WTF.init( 'key' );`. Looking at your source code it's `0AvG1Hx204EyydF9ub1M2cVJ3Z1VGdDhTSWg0ZV9LNGc` - is that loading the correct data for you? When I load it it has the default data in it.

**Comment by Nuku** [comment]
It looks to be working right for me now?
 1XTuzrWzLtfvb_gQocHK-6PIBKdbhAU_aYnsT3ddrbVs

**Comment by soulwire** [comment]
Great, yeah that's working when I load it locally too. Glad it's fixed! :)

**Comment by Nuku** [comment]
Thanks again for the speedy fix!

**Comment by soulwire** [comment]
No problem. You reminded me I needed to sort this bug so thanks for filing the issue and sorry your site was broke for a little while.

**Comment by Dalkarl** [comment]
Hi! I have the same problem with my Google Spreadsheet, it just gets to an infinite load: https://talanrien.com/chargen/
Is there something that can be fixed?
