### ISSUE TITLE
Add to showcase?

### ISSUE THREAD

**Issue by phillbaker** [soulwire/WTFEngine#28]
Thanks for putting this together, it makes setting these up super easy!

Just wanted to drop a link to another example, if you wanted to add to the readme: http://wtfismybot.tech/ (https://github.com/phillbaker/wtfismybotstrategy).

**Comment by soulwire** [comment]
Super late picking this up—was about to add it to the showcase but looks like it's down?

**Comment by phillbaker** [comment]
Whoops! Sorry for my slow response on this. Should be back up :grinning:

**Comment by phillbaker** [comment]
Thanks!
